

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
mypy_path = ["src"]

# Ignore import errors
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "lades.settings"

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
lines_after_imports = 2
known_first_party = ["lades"]
